language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    #- extra-android-support
script:
- ./gradlew assembleRelease
before_install:
- openssl aes-256-cbc -K $termux_key -iv $termux_iv -in keys/termux.keystore.enc -out keys/termux.keystore -d
- openssl aes-256-cbc -K $travis_key -iv $travis_iv -in keys/travis.enc -out travis -d
deploy:
  #notification_email: choqingwang@foxmail.com
  provider: releases
  api_key:
    secure: IkjmWwRYUzzqAnmntKSXnr8LAIEXsl2K+FKBZGAFd0hVTo3Zv6DJvubb7UH7KPUZLM3CQC7Pm5OJ9cgpL7dyPXKV5FygMjFgJUdM02CSl5QLL/7Dr9Sbf6h2YzmM+S/Dxs0zZkhjOk1X5JnVADIjpNJQCUUn9gFL8jFnJHjwtSQF6OwXPggwHlefvhSo8FQ7Q+pO0B9YMq4bP/iwf4ZY+d+g3552wOdlsy3VKR4kcZa+EjSa18IejJe83uJDjRnA6pn4sH2LeUkds/BiATJmX/wdtqjLmYftRYOdl15QFCuNYMNvcbHQ8yUIrsDCIlSrYgWJeXFWXA5XIh3S2bwPC4hyoQ7l2CaLn+6a6/l4jbIdyt3/2MZeiW/yMQkAnl4WKN4c0DA0RGh46oppNk0QsswSMHvD2Ui09rXx35ulWyqJMxKqQOIzmw7kWWq1KWhIsXq32QjabA1NN4ZT70QLArUfYy+nj5LDcWSWJqkuljXm4m4kPeGOLKGvSCjpfGeHUw1V3mUjhbktIkt1CuvqiD3rxq//sxw3xTVV9xJCFqB1RPiLIbAVtIdL9Ukh21BGhqo/UWlvI7HDHTAcHaoyQXc+5FkPMkTxMAMGj5vzVqRkU8hARelg/5O/DoreTUO4uj2gWlDWkD3634YSMyRHs1+dhhYp98Bjk5Pvqjd7vh0=
  file: app/build/outputs/apk/termux.widget-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
