language: android  
android:  
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:  
  - ./gradlew assembleRelease
  - find . -type f
#deploy:  
  #provider: releases
  #api_key: "GITHUB OAUTH TOKEN"
  #file: "FILE TO UPLOAD"
  #skip_cleanup: true
  #on:
    #tags: true
